import { AbilityLevels, Genders, Heights, BootSizes } from "../types/RentalForm"

export const abilityLevels: AbilityLevels[] = [
    {value: 'beginner', display: 'Beginner'},
    {value: 'intermediate', display: 'Intermediate'},
    {value: 'advanced', display: 'Advanced'},
    {value: 'expert', display: 'Expert'},
]

export const genders: Genders[] = [
    {value: 'female', display: 'Female'},
    {value: 'male', display: 'Male'},
    {value: '?', display: '???'},
]

export const bootSizes: BootSizes[] = [
    {value: `5`, display: `5`},
    {value: `5.5`, display: `5.5`},
    {value: `6`, display: `6`},
    {value: `6.5`, display: `6.5`},
    {value: `7`, display: `7`},
    {value: `7.5`, display: `7.5`},
    {value: `8`, display: `8`},
    {value: `8.5`, display: `8.5`},
    {value: `9`, display: `9`},
    {value: `9.5`, display: `9.5`},
    {value: `10`, display: `10`},
    {value: `10.5`, display: `10.5`},
    {value: `11`, display: `11`},
    {value: `11.5`, display: `11.5`},
    {value: `12`, display: `12`},
    {value: `12.5`, display: `12.5`},
    {value: `13`, display: `13`},
    {value: `14`, display: `14`},
]

export const heights: Heights[] = [
    {value: `4'0"`, display: `4'0"`},
    {value: `4'1"`, display: `4'1"`},
    {value: `4'2"`, display: `4'2"`},
    {value: `4'3"`, display: `4'3"`},
    {value: `4'4"`, display: `4'4"`},
    {value: `4'5"`, display: `4'5"`},
    {value: `4'6"`, display: `4'6"`},
    {value: `4'7"`, display: `4'7"`},
    {value: `4'8"`, display: `4'8"`},
    {value: `4'9"`, display: `4'9"`},
    {value: `4'10"`, display: `4'10"`},
    {value: `4'11"`, display: `4'11"`},
    {value: `5'0"`, display: `5'0"`},
    {value: `5'1"`, display: `5'1"`},
    {value: `5'2"`, display: `5'2"`},
    {value: `5'3"`, display: `5'3"`},
    {value: `5'4"`, display: `5'4"`},
    {value: `5'5"`, display: `5'5"`},
    {value: `5'6"`, display: `5'6"`},
    {value: `5'7"`, display: `5'7"`},
    {value: `5'8"`, display: `5'8"`},
    {value: `5'9"`, display: `5'9"`},
    {value: `5'10"`, display: `5'10"`},
    {value: `5'11"`, display: `5'11"`},
    {value: `6'0"`, display: `6'0"`},
    {value: `6'1"`, display: `6'1"`},
    {value: `6'2"`, display: `6'2"`},
    {value: `6'3"`, display: `6'3"`},
    {value: `6'4"`, display: `6'4"`},
    {value: `6'5"`, display: `6'5"`},
    {value: `6'6"`, display: `6'6"`},
    {value: `6'7"`, display: `6'7"`},
    {value: `6'8"`, display: `6'8"`},
    {value: `6'9"`, display: `6'9"`},
    {value: `6'10"`, display: `6'10"`},
    {value: `6'11"`, display: `6'11"`},
]

