// AUTH
export const USER_HAS_AUTHENTICATED = "USER_HAS_AUTHENTICATED"

// UI
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR'
export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS'
export const LOADING_BAR = 'LOADING_BAR'

// RIDERS
export const ADD_RIDER = 'ADD_RIDER'
